---

- hosts: galaxyservers
  become: true
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['git', 'make', 'python3-psycopg2', 'virtualenv']
    - name: Install nginx-extras repository
      apt_repository:
        repo: ppa:galaxyproject/nginx
  handlers:
    - name: Restart Galaxy
      systemd:
        name: galaxy
        state: restarted
  roles:
    - test-role
